baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "basic"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[mediaTypes]
  [mediaTypes."text/markdown"]
    suffixes = ["md", "markdown", "mdown", "mkd", "mkdn"]
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  taxonomy = ["HTML", "RSS", "JSON"]
  term = ["HTML", "RSS", "JSON"]

